// Mocks generated by Mockito 5.4.4 from annotations
// in nonna_app/test/core/services/data_export_handler_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:nonna_app/core/services/backup_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BackupService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBackupService extends _i1.Mock implements _i2.BackupService {
  MockBackupService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> exportUserData(String? userId) => (super.noSuchMethod(
        Invocation.method(
          #exportUserData,
          [userId],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #exportUserData,
            [userId],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<List<String>> backupPhotos(
    String? userId, {
    String? babyProfileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #backupPhotos,
          [userId],
          {#babyProfileId: babyProfileId},
        ),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<void> restoreFromBackup(
    String? userId,
    String? backupData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreFromBackup,
          [
            userId,
            backupData,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> hasAutomaticBackupsEnabled(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasAutomaticBackupsEnabled,
          [userId],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> scheduleAutomaticBackup(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleAutomaticBackup,
          [userId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<DateTime?> getLastBackupDate(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLastBackupDate,
          [userId],
        ),
        returnValue: _i3.Future<DateTime?>.value(),
      ) as _i3.Future<DateTime?>);
}
