// Mocks generated by Mockito 5.4.4 from annotations
// in nonna_app/test/features/baby_profile/presentation/providers/baby_profile_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [DatabaseService].
class MockDatabaseService extends _i1.Mock {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  dynamic select(String? table) => super.noSuchMethod(
        Invocation.method(#select, [table]),
        returnValueForMissingStub: null,
      );

  dynamic insert(String? table, Map<String, dynamic>? data) =>
      super.noSuchMethod(
        Invocation.method(#insert, [table, data]),
        returnValueForMissingStub: null,
      );

  dynamic update(String? table, Map<String, dynamic>? data) =>
      super.noSuchMethod(
        Invocation.method(#update, [table, data]),
        returnValueForMissingStub: null,
      );

  dynamic delete(String? table) => super.noSuchMethod(
        Invocation.method(#delete, [table]),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [CacheService].
class MockCacheService extends _i1.Mock {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  bool get isInitialized => super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
        returnValueForMissingStub: false,
      );

  _i2.Future<dynamic> get(String? key) => super.noSuchMethod(
        Invocation.method(#get, [key]),
        returnValue: _i2.Future<dynamic>.value(),
        returnValueForMissingStub: _i2.Future<dynamic>.value(),
      );

  _i2.Future<void> put(
    String? key,
    dynamic value, {
    int? ttlMinutes,
  }) =>
      super.noSuchMethod(
        Invocation.method(#put, [key, value], {#ttlMinutes: ttlMinutes}),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      );

  _i2.Future<void> remove(String? key) => super.noSuchMethod(
        Invocation.method(#remove, [key]),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      );

  _i2.Future<void> clear() => super.noSuchMethod(
        Invocation.method(#clear, []),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      );
}

/// A class which mocks [StorageService].
class MockStorageService extends _i1.Mock {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  _i2.Future<String> uploadFile({
    required String? filePath,
    required String? storageKey,
    required String? bucket,
  }) =>
      super.noSuchMethod(
        Invocation.method(#uploadFile, [], {
          #filePath: filePath,
          #storageKey: storageKey,
          #bucket: bucket,
        }),
        returnValue: _i2.Future<String>.value(''),
        returnValueForMissingStub: _i2.Future<String>.value(''),
      );

  _i2.Future<void> deleteFile({
    required String? storageKey,
    required String? bucket,
  }) =>
      super.noSuchMethod(
        Invocation.method(#deleteFile, [], {
          #storageKey: storageKey,
          #bucket: bucket,
        }),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      );
}
