// Mocks generated by Mockito 5.4.4 from annotations
// in nonna_app/test/features/profile/presentation/providers/profile_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i4;
import 'dart:typed_data' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:nonna_app/core/models/owner_update_marker.dart' as _i7;
import 'package:nonna_app/core/services/cache_service.dart' as _i6;
import 'package:nonna_app/core/services/database_service.dart' as _i3;
import 'package:nonna_app/core/services/storage_service.dart' as _i8;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostgrestFilterBuilder_0<T> extends _i1.SmartFake
    implements _i2.PostgrestFilterBuilder<T> {
  _FakePostgrestFilterBuilder_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginatedResult_1 extends _i1.SmartFake
    implements _i3.PaginatedResult {
  _FakePaginatedResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFile_2 extends _i1.SmartFake implements _i4.File {
  _FakeFile_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostgrestFilterBuilder<List<Map<String, dynamic>>> select(
    String? table, {
    String? columns = r'*',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#columns: columns},
        ),
        returnValue: _FakePostgrestFilterBuilder_0<List<Map<String, dynamic>>>(
          this,
          Invocation.method(
            #select,
            [table],
            {#columns: columns},
          ),
        ),
      ) as _i2.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> insert(
    String? table,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            data,
          ],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> insertMany(
    String? table,
    List<Map<String, dynamic>>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMany,
          [
            table,
            data,
          ],
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> update(
    String? table,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            data,
          ],
        ),
        returnValue: _FakePostgrestFilterBuilder_0<dynamic>(
          this,
          Invocation.method(
            #update,
            [
              table,
              data,
            ],
          ),
        ),
      ) as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i5.Future<List<Map<String, dynamic>>> upsert(
    String? table,
    Map<String, dynamic>? data, {
    String? onConflict,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsert,
          [
            table,
            data,
          ],
          {#onConflict: onConflict},
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<List<Map<String, dynamic>>> upsertMany(
    String? table,
    List<Map<String, dynamic>>? data, {
    String? onConflict,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMany,
          [
            table,
            data,
          ],
          {#onConflict: onConflict},
        ),
        returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> delete(String? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakePostgrestFilterBuilder_0<dynamic>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i5.Future<dynamic> rpc(
    String? functionName, {
    Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rpc,
          [functionName],
          {#params: params},
        ),
        returnValue: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);

  @override
  _i5.Future<_i3.PaginatedResult> getPaginated(
    String? table, {
    required int? page,
    required int? pageSize,
    String? columns = r'*',
    String? orderBy,
    bool? ascending = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaginated,
          [table],
          {
            #page: page,
            #pageSize: pageSize,
            #columns: columns,
            #orderBy: orderBy,
            #ascending: ascending,
          },
        ),
        returnValue:
            _i5.Future<_i3.PaginatedResult>.value(_FakePaginatedResult_1(
          this,
          Invocation.method(
            #getPaginated,
            [table],
            {
              #page: page,
              #pageSize: pageSize,
              #columns: columns,
              #orderBy: orderBy,
              #ascending: ascending,
            },
          ),
        )),
      ) as _i5.Future<_i3.PaginatedResult>);

  @override
  _i5.Future<void> executeTransaction(
    String? transactionFunctionName, {
    Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeTransaction,
          [transactionFunctionName],
          {#params: params},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> batchInsert(
    String? table,
    List<Map<String, dynamic>>? data, {
    int? batchSize = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchInsert,
          [
            table,
            data,
          ],
          {#batchSize: batchSize},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> exists(
    String? table, {
    required String? column,
    required dynamic value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exists,
          [table],
          {
            #column: column,
            #value: value,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> count(String? table) => (super.noSuchMethod(
        Invocation.method(
          #count,
          [table],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i6.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i5.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> put(
    String? key,
    dynamic data, {
    int? ttlMinutes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            data,
          ],
          {#ttlMinutes: ttlMinutes},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<T?> get<T>(String? key) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
        ),
        returnValue: _i5.Future<T?>.value(),
      ) as _i5.Future<T?>);

  @override
  _i5.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> has(String? key) => (super.noSuchMethod(
        Invocation.method(
          #has,
          [key],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> invalidateByOwnerUpdate(
    String? babyProfileId,
    _i7.OwnerUpdateMarker? ownerUpdateMarker,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #invalidateByOwnerUpdate,
          [
            babyProfileId,
            ownerUpdateMarker,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> invalidateByBabyProfile(String? babyProfileId) =>
      (super.noSuchMethod(
        Invocation.method(
          #invalidateByBabyProfile,
          [babyProfileId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> getCacheSize() => (super.noSuchMethod(
        Invocation.method(
          #getCacheSize,
          [],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> cleanupExpired() => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpired,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  List<String> getAllKeys() => (super.noSuchMethod(
        Invocation.method(
          #getAllKeys,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i8.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i4.File?> pickImageFromGallery({
    int? quality = 70,
    int? maxWidth = 1920,
    int? maxHeight = 1920,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickImageFromGallery,
          [],
          {
            #quality: quality,
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
          },
        ),
        returnValue: _i5.Future<_i4.File?>.value(),
      ) as _i5.Future<_i4.File?>);

  @override
  _i5.Future<_i4.File?> pickImageFromCamera({
    int? quality = 70,
    int? maxWidth = 1920,
    int? maxHeight = 1920,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pickImageFromCamera,
          [],
          {
            #quality: quality,
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
          },
        ),
        returnValue: _i5.Future<_i4.File?>.value(),
      ) as _i5.Future<_i4.File?>);

  @override
  _i5.Future<_i9.Uint8List?> compressImageBytes(
    _i9.Uint8List? imageBytes, {
    int? quality = 70,
    int? maxWidth = 1920,
    int? maxHeight = 1920,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #compressImageBytes,
          [imageBytes],
          {
            #quality: quality,
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
          },
        ),
        returnValue: _i5.Future<_i9.Uint8List?>.value(),
      ) as _i5.Future<_i9.Uint8List?>);

  @override
  _i5.Future<String> uploadGalleryPhoto({
    required _i4.File? imageFile,
    required String? babyProfileId,
    String? caption,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadGalleryPhoto,
          [],
          {
            #imageFile: imageFile,
            #babyProfileId: babyProfileId,
            #caption: caption,
            #tags: tags,
          },
        ),
        returnValue: _i5.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #uploadGalleryPhoto,
            [],
            {
              #imageFile: imageFile,
              #babyProfileId: babyProfileId,
              #caption: caption,
              #tags: tags,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> uploadUserAvatar({
    required _i4.File? imageFile,
    required String? userId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadUserAvatar,
          [],
          {
            #imageFile: imageFile,
            #userId: userId,
          },
        ),
        returnValue: _i5.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #uploadUserAvatar,
            [],
            {
              #imageFile: imageFile,
              #userId: userId,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> uploadBabyProfilePhoto({
    required _i4.File? imageFile,
    required String? babyProfileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadBabyProfilePhoto,
          [],
          {
            #imageFile: imageFile,
            #babyProfileId: babyProfileId,
          },
        ),
        returnValue: _i5.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #uploadBabyProfilePhoto,
            [],
            {
              #imageFile: imageFile,
              #babyProfileId: babyProfileId,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> uploadEventPhoto({
    required _i4.File? imageFile,
    required String? babyProfileId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadEventPhoto,
          [],
          {
            #imageFile: imageFile,
            #babyProfileId: babyProfileId,
          },
        ),
        returnValue: _i5.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #uploadEventPhoto,
            [],
            {
              #imageFile: imageFile,
              #babyProfileId: babyProfileId,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  String getPublicUrl(
    String? bucketName,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicUrl,
          [
            bucketName,
            path,
          ],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #getPublicUrl,
            [
              bucketName,
              path,
            ],
          ),
        ),
      ) as String);

  @override
  _i5.Future<String> getSignedUrl(
    String? bucketName,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSignedUrl,
          [
            bucketName,
            path,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i10.dummyValue<String>(
          this,
          Invocation.method(
            #getSignedUrl,
            [
              bucketName,
              path,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  String getOptimizedImageUrl({
    required String? bucketName,
    required String? path,
    int? width,
    int? height,
    String? quality = r'auto',
    String? format = r'webp',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOptimizedImageUrl,
          [],
          {
            #bucketName: bucketName,
            #path: path,
            #width: width,
            #height: height,
            #quality: quality,
            #format: format,
          },
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #getOptimizedImageUrl,
            [],
            {
              #bucketName: bucketName,
              #path: path,
              #width: width,
              #height: height,
              #quality: quality,
              #format: format,
            },
          ),
        ),
      ) as String);

  @override
  _i5.Future<void> deleteFile(
    String? bucketName,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [
            bucketName,
            path,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteFiles(
    String? bucketName,
    List<String>? paths,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFiles,
          [
            bucketName,
            paths,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<String>> batchUploadPhotos({
    required List<_i4.File>? imageFiles,
    required String? babyProfileId,
    List<String>? captions,
    List<List<String>>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchUploadPhotos,
          [],
          {
            #imageFiles: imageFiles,
            #babyProfileId: babyProfileId,
            #captions: captions,
            #tags: tags,
          },
        ),
        returnValue: _i5.Future<List<String>>.value(<String>[]),
      ) as _i5.Future<List<String>>);

  @override
  _i5.Future<_i4.File> generateThumbnail(
    _i4.File? imageFile, {
    int? maxWidth = 300,
    int? maxHeight = 300,
    int? quality = 60,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateThumbnail,
          [imageFile],
          {
            #maxWidth: maxWidth,
            #maxHeight: maxHeight,
            #quality: quality,
          },
        ),
        returnValue: _i5.Future<_i4.File>.value(_FakeFile_2(
          this,
          Invocation.method(
            #generateThumbnail,
            [imageFile],
            {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #quality: quality,
            },
          ),
        )),
      ) as _i5.Future<_i4.File>);

  @override
  _i5.Future<Map<String, String>> uploadPhotoWithThumbnail({
    required _i4.File? imageFile,
    required String? babyProfileId,
    String? caption,
    List<String>? tags,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadPhotoWithThumbnail,
          [],
          {
            #imageFile: imageFile,
            #babyProfileId: babyProfileId,
            #caption: caption,
            #tags: tags,
          },
        ),
        returnValue: _i5.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i5.Future<Map<String, String>>);

  @override
  _i5.Future<int> getStorageUsage(String? babyProfileId) => (super.noSuchMethod(
        Invocation.method(
          #getStorageUsage,
          [babyProfileId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> hasStorageQuota(
    String? babyProfileId, {
    int? maxStorageMb = 500,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #hasStorageQuota,
          [babyProfileId],
          {#maxStorageMb: maxStorageMb},
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}
