// Mocks generated by Mockito 5.4.4 from annotations
// in nonna_app/test/tiles/registry_deals/providers/registry_deals_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nonna_app/core/models/owner_update_marker.dart' as _i6;
import 'package:nonna_app/core/services/cache_service.dart' as _i5;
import 'package:nonna_app/core/services/database_service.dart' as _i3;
import 'package:supabase_flutter/supabase_flutter.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePostgrestFilterBuilder_0<T> extends _i1.SmartFake
    implements _i2.PostgrestFilterBuilder<T> {
  _FakePostgrestFilterBuilder_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePaginatedResult_1 extends _i1.SmartFake
    implements _i3.PaginatedResult {
  _FakePaginatedResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PostgrestFilterBuilder<List<Map<String, dynamic>>> select(
    String? table, {
    String? columns = r'*',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#columns: columns},
        ),
        returnValue: _FakePostgrestFilterBuilder_0<List<Map<String, dynamic>>>(
          this,
          Invocation.method(
            #select,
            [table],
            {#columns: columns},
          ),
        ),
      ) as _i2.PostgrestFilterBuilder<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> insert(
    String? table,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [
            table,
            data,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> insertMany(
    String? table,
    List<Map<String, dynamic>>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertMany,
          [
            table,
            data,
          ],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> update(
    String? table,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [
            table,
            data,
          ],
        ),
        returnValue: _FakePostgrestFilterBuilder_0<dynamic>(
          this,
          Invocation.method(
            #update,
            [
              table,
              data,
            ],
          ),
        ),
      ) as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i4.Future<List<Map<String, dynamic>>> upsert(
    String? table,
    Map<String, dynamic>? data, {
    String? onConflict,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsert,
          [
            table,
            data,
          ],
          {#onConflict: onConflict},
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> upsertMany(
    String? table,
    List<Map<String, dynamic>>? data, {
    String? onConflict,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #upsertMany,
          [
            table,
            data,
          ],
          {#onConflict: onConflict},
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i2.PostgrestFilterBuilder<dynamic> delete(String? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakePostgrestFilterBuilder_0<dynamic>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i2.PostgrestFilterBuilder<dynamic>);

  @override
  _i4.Future<dynamic> rpc(
    String? functionName, {
    Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #rpc,
          [functionName],
          {#params: params},
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<_i3.PaginatedResult> getPaginated(
    String? table, {
    required int? page,
    required int? pageSize,
    String? columns = r'*',
    String? orderBy,
    bool? ascending = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPaginated,
          [table],
          {
            #page: page,
            #pageSize: pageSize,
            #columns: columns,
            #orderBy: orderBy,
            #ascending: ascending,
          },
        ),
        returnValue:
            _i4.Future<_i3.PaginatedResult>.value(_FakePaginatedResult_1(
          this,
          Invocation.method(
            #getPaginated,
            [table],
            {
              #page: page,
              #pageSize: pageSize,
              #columns: columns,
              #orderBy: orderBy,
              #ascending: ascending,
            },
          ),
        )),
      ) as _i4.Future<_i3.PaginatedResult>);

  @override
  _i4.Future<void> executeTransaction(
    String? transactionFunctionName, {
    Map<String, dynamic>? params,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #executeTransaction,
          [transactionFunctionName],
          {#params: params},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> batchInsert(
    String? table,
    List<Map<String, dynamic>>? data, {
    int? batchSize = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #batchInsert,
          [
            table,
            data,
          ],
          {#batchSize: batchSize},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> exists(
    String? table, {
    required String? column,
    required dynamic value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exists,
          [table],
          {
            #column: column,
            #value: value,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> count(String? table) => (super.noSuchMethod(
        Invocation.method(
          #count,
          [table],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);
}

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i5.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<void> initialize({bool? testMode = false}) => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
          {#testMode: testMode},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() => (super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> put(
    String? key,
    dynamic data, {
    int? ttlMinutes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            data,
          ],
          {#ttlMinutes: ttlMinutes},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<T?> get<T>(String? key) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
        ),
        returnValue: _i4.Future<T?>.value(),
      ) as _i4.Future<T?>);

  @override
  _i4.Future<void> delete(String? key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<bool> has(String? key) => (super.noSuchMethod(
        Invocation.method(
          #has,
          [key],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<void> invalidateByOwnerUpdate(
    String? babyProfileId,
    _i6.OwnerUpdateMarker? ownerUpdateMarker,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #invalidateByOwnerUpdate,
          [
            babyProfileId,
            ownerUpdateMarker,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> invalidateByBabyProfile(String? babyProfileId) =>
      (super.noSuchMethod(
        Invocation.method(
          #invalidateByBabyProfile,
          [babyProfileId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> getCacheSize() => (super.noSuchMethod(
        Invocation.method(
          #getCacheSize,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> cleanupExpired() => (super.noSuchMethod(
        Invocation.method(
          #cleanupExpired,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  List<String> getAllKeys() => (super.noSuchMethod(
        Invocation.method(
          #getAllKeys,
          [],
        ),
        returnValue: <String>[],
      ) as List<String>);
}
