import 'package:firebase_core/firebase_core.dart';

/// Firebase configuration options
/// These will be generated by FlutterFire CLI
/// Run: flutterfire configure
class FirebaseConfig {
  /// Get current platform Firebase options.
  /// Returning null tells Firebase to read from the natively bundled
  /// google-services.json (Android) and GoogleService-Info.plist (iOS).
  static FirebaseOptions? get currentPlatform {
    return null;
  }
}
